#include "arduino_pins.h"
#include "board_pins.h"

const ArduinoPinMap_t g_arduinoPinMap[NUM_LOGICAL_PINS] =
{
    /* 0  - D0 */
    { BOARD_GPIO0_PORT, BOARD_GPIO0_GPIO, BOARD_GPIO0_PIN, PIN_FUNC_DIGITAL },

    /* 1  - D1 */
    { BOARD_GPIO1_PORT, BOARD_GPIO1_GPIO, BOARD_GPIO1_PIN, PIN_FUNC_DIGITAL },

    /* 2  - D2 */
    { BOARD_GPIO2_PORT, BOARD_GPIO2_GPIO, BOARD_GPIO2_PIN, PIN_FUNC_DIGITAL },

    /* 3  - D3 */
    { BOARD_GPIO3_PORT, BOARD_GPIO3_GPIO, BOARD_GPIO3_PIN, PIN_FUNC_DIGITAL },

    /* 4  - D4 */
    { BOARD_GPIO4_PORT, BOARD_GPIO4_GPIO, BOARD_GPIO4_PIN, PIN_FUNC_DIGITAL },

    /* 5  - D5 */
    { BOARD_GPIO5_PORT, BOARD_GPIO5_GPIO, BOARD_GPIO5_PIN, PIN_FUNC_DIGITAL },

    /* 6  - D6 */
    { BOARD_GPIO6_PORT, BOARD_GPIO6_GPIO, BOARD_GPIO6_PIN, PIN_FUNC_DIGITAL },

    /* 7  - D7 */
    { BOARD_GPIO7_PORT, BOARD_GPIO7_GPIO, BOARD_GPIO7_PIN, PIN_FUNC_DIGITAL },

    /* 8  - D8 */
    { BOARD_GPIO8_PORT, BOARD_GPIO8_GPIO, BOARD_GPIO8_PIN, PIN_FUNC_DIGITAL },

    /* 9  - D9 */
    { BOARD_GPIO9_PORT, BOARD_GPIO9_GPIO, BOARD_GPIO9_PIN, PIN_FUNC_DIGITAL },

    /* 10 - LED_RED */
    { BOARD_LED_RED_PORT, BOARD_LED_RED_GPIO, BOARD_LED_RED_PIN, PIN_FUNC_LED },

    /* 11 - LED_BLUE */
    { BOARD_LED_BLUE_PORT, BOARD_LED_BLUE_GPIO, BOARD_LED_BLUE_PIN, PIN_FUNC_LED },

    /* 12 - LED_GREEN */
    { BOARD_LED_GREEN_PORT, BOARD_LED_GREEN_GPIO, BOARD_LED_GREEN_PIN, PIN_FUNC_LED },

    /* 13 - BTN0 */
    { BOARD_BUTTON0_PORT, BOARD_BUTTON0_GPIO, BOARD_BUTTON0_PIN, PIN_FUNC_BUTTON },

    /* 14 - BTN1 */
    { BOARD_BUTTON1_PORT, BOARD_BUTTON1_GPIO, BOARD_BUTTON1_PIN, PIN_FUNC_BUTTON },

    /* 15 - CAN_TX_PIN */
    { BOARD_CAN_TX_PORT, BOARD_CAN_TX_GPIO, BOARD_CAN_TX_PIN, PIN_FUNC_CAN },

    /* 16 - CAN_RX_PIN */
    { BOARD_CAN_RX_PORT, BOARD_CAN_RX_GPIO, BOARD_CAN_RX_PIN, PIN_FUNC_CAN },

    /* 17 - SPI_SCK_PIN */
    { BOARD_SBC_SCK_PORT, BOARD_SBC_SCK_GPIO, BOARD_SBC_SCK_PIN, PIN_FUNC_SPI },

    /* 18 - SPI_MISO_PIN */
    { BOARD_SBC_MISO_PORT, BOARD_SBC_MISO_GPIO, BOARD_SBC_MISO_PIN, PIN_FUNC_SPI },

    /* 19 - SPI_MOSI_PIN */
    { BOARD_SBC_MOSI_PORT, BOARD_SBC_MOSI_GPIO, BOARD_SBC_MOSI_PIN, PIN_FUNC_SPI },

    /* 20 - SPI_CS_PIN */
    { BOARD_SBC_CS_PORT, BOARD_SBC_CS_GPIO, BOARD_SBC_CS_PIN, PIN_FUNC_SPI },

    /* 21 - I2C_SCL_PIN */
    { BOARD_I2C0_SCL_PORT, BOARD_I2C0_SCL_GPIO, BOARD_I2C0_SCL_PIN, PIN_FUNC_I2C },

    /* 22 - I2C_SDA_PIN */
    { BOARD_I2C0_SDA_PORT, BOARD_I2C0_SDA_GPIO, BOARD_I2C0_SDA_PIN, PIN_FUNC_I2C },

    /* 23 - UART1_RX_PIN */
    { BOARD_UART1_RX_PORT, BOARD_UART1_RX_GPIO, BOARD_UART1_RX_PIN, PIN_FUNC_UART },

    /* 24 - UART1_TX_PIN */
    { BOARD_UART1_TX_PORT, BOARD_UART1_TX_GPIO, BOARD_UART1_TX_PIN, PIN_FUNC_UART },

    /* 25 - UART2_RX_PIN */
    { BOARD_UART2_RX_PORT, BOARD_UART2_RX_GPIO, BOARD_UART2_RX_PIN, PIN_FUNC_UART },

    /* 26 - UART2_TX_PIN */
    { BOARD_UART2_TX_PORT, BOARD_UART2_TX_GPIO, BOARD_UART2_TX_PIN, PIN_FUNC_UART },

    /* 27 - A0 */
    { BOARD_ADC0_SE12_PORT, BOARD_ADC0_SE12_GPIO, BOARD_ADC0_SE12_PIN, PIN_FUNC_ANALOG },

    /* 28 - A1 */
    { BOARD_ADC0_SE13_PORT, BOARD_ADC0_SE13_GPIO, BOARD_ADC0_SE13_PIN, PIN_FUNC_ANALOG }
};

uint8_t Arduino_IsValidPin(uint8_t pin)
{
    return (ARDUINO_IS_VALID_PIN(pin)) ? 1U : 0U;
}

uint8_t Arduino_IsDigitalPin(uint8_t pin)
{
    if (!Arduino_IsValidPin(pin))
    {
        return 0U;
    }

    switch (g_arduinoPinMap[pin].function)
    {
        case PIN_FUNC_DIGITAL:
        case PIN_FUNC_LED:
        case PIN_FUNC_BUTTON:
            return 1U;

        default:
            return 0U;
    }
}

uint8_t Arduino_IsAnalogPin(uint8_t pin)
{
    if (!Arduino_IsValidPin(pin))
    {
        return 0U;
    }

    return (g_arduinoPinMap[pin].function == PIN_FUNC_ANALOG) ? 1U : 0U;
}